### ISSUE TITLE
Make sure that FogROS 2 can work from a generic Ubuntu AMI (i.e., install from scratch)

### ISSUE THREAD

**Issue by jeffi** [BerkeleyAutomation/FogROS2#101]
**Describe the bug**
To better support the `image` CLI, we should make FogROS2 work with the most generic Ubuntu AMI available.  That way, starting from any other AMI will likely work.  Main issues seem to be making sure FogROS2 install any missing dependencies.

**To Reproduce**
1. Run talker example, but using generic Ubuntu 22.04 AMI
2. Check for messages related to missing dependencies.

**Comment by zhanhugo** [comment]
Merged into ICRA2023-Review
