### ISSUE TITLE
Release into Humble

### ISSUE THREAD

**Issue by vmayoral** [BerkeleyAutomation/FogROS2#15]
*This ticket tracks the process of releasing FogROS2 core package into [ROS 2 Humble](https://docs.ros.org/en/rolling/Releases/Release-Humble-Hawksbill.html#release-timeline).  Dates are pretty tight, so we'll play by the ear and hope for the best*.

- [x] prepare for release:
  - [x] code review for release
    - [x] Update SECURITY document, remove guidelines since they didn't make it to the paper
    - [x] Remove duplicate code
    - [x] LICENSE for the meta-package
    - [x] Add CHANGELOG.rst to the two packages to release `fogros2` and `fogros2_launch`
    - [x] Re-structure `fogros2_launch` to look like a real package
    - [x] Remove duplicated code in FogROS2 launch extensions `fogros2_launch` (ping @jeffi and @KeplerC, there's currently lots of duplicated code and we should only include the extensions)
    - [x] code re-formatting (extract examples and h264 into separate packages, as agreed)
    - [x] review dependencies for `fogros2` and `fogros2_launch` in package.xml files
    - [x] re-validate functionality
      - [x] Bring Dockerfile to Rolling 195235cb8f153cc6bda9225be56178e00e3bac95
      - [x] Return to Galactic due to unstabilities 9388bb3651b6ac6b1af6ade674e538facf9a6614, see #16 
      - [x] Validated fog CLI extension verb and subverbs
      - [x] ⚠️ Simple pub/sub example 
        - [x] ❌ https://github.com/BerkeleyAutomation/FogROS2/issues/19
        - [x] ❌ https://github.com/BerkeleyAutomation/FogROS2/issues/27
        - [ ] https://github.com/BerkeleyAutomation/FogROS2/issues/18
        - [x] https://github.com/BerkeleyAutomation/FogROS2/issues/17
    - [x] Review `README.md`
      - [x] Basic instructions and working 3a08469c80316801e1157ce600333840ba0107ec
  - [x] release branches
  - [x] release tags
- [x] release
  - [x] Create release repo https://github.com/ros2-gbp/ros2-gbp-github-org/pull/42
  - [x] Do [`bloom` release](https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease) https://github.com/ros2-gbp/fogros2-release
    - [x] `bloom` should PR `rosdistro`, if not, **manually create a PR** 
  - [x] `rosdistro` team to review package and merge PR (1-2 days, 1 month to get apt installable)
  - [x] Monitor build and release status on [repo page](http://repo.ros2.org/status_page/) and [buildfarm](https://build.ros2.org/)
  - [x] Bloom for `humble`

**Comment by vmayoral** [comment]
Started working on the release process in the `main` branch. Quite a bit of work left to be done refactoring code. Will look at this in the coming few days as time allows for it.

Will try to in parallel advance with requests for the release.

**Comment by vmayoral** [comment]
Sent the request to create the team and the release repo https://github.com/ros2-gbp/ros2-gbp-github-org/pull/42. Need to wait now for approval. In parallel we should be fulfilling the items on "*prepare for release*" above.

**Comment by vmayoral** [comment]
Encountering quite a few inconsistencies in naming across the source code. @jeffi and @KeplerC, are we going for `FogROS2` or for `FogROS 2`, or maybe instead (simpler) `fogros2`?

**Comment by vmayoral** [comment]
Spent a few hours re-reviewing simple execution example of Cloud Nodes and I wasn't able to get https://github.com/BerkeleyAutomation/FogROS2/blob/main/fogros2_examples/launch/talker.launch.py running. This deserves further attention as highlighted in https://github.com/BerkeleyAutomation/FogROS2/issues/19.

As is, I'd say we should hold the Humble release until basic examples are stable enough.

**Comment by vmayoral** [comment]
Update, we've got the repos now https://github.com/ros2-gbp/ros2-gbp-github-org/pull/42#event-6411912498. I can confirm access to https://github.com/ros2-gbp/fogros2-release. Once outstanding issues of code functionality are addressed, we should be able to submit a bloom release and then follow up with a rosdistro PR.

**Comment by vmayoral** [comment]
Shall we close this folks?

**Comment by KDharmarajanDev** [comment]
Release is successful, closing this issue.
