### ISSUE TITLE
Make launching Foxglove optional

### ISSUE THREAD

**Issue by jeffi** [BerkeleyAutomation/FogROS2#21]
Currently Foxglove appears to launch regardless if it is enabled or not.  This can add unnecessary overhead.  Let's make Foxglove only launch when configured.

**Comment by mjd3** [comment]
@jeffi Let me know if this can be closed by #26

**Comment by SimeonOA** [comment]
Pending Review

**Comment by mjd3** [comment]
This is fixed by #41. Thanks @zhanhugo!
