### ISSUE TITLE
Change from using `/tmp/fogros` to using `~/.fogros2`

### ISSUE THREAD

**Issue by jeffi** [BerkeleyAutomation/FogROS2#37]
Currently temporary and persistent files are placed in `/tmp`. System processes might delete contents of `/tmp`, hindering their access.

Proposed solution: use `~/.fogros2` for all persistent files.

**Comment by jeffi** [comment]
Fix checked in.  Also centralized location of path.  c57ea5477aec737a75176b67d8d2170cfbcb4608

**Comment by KeplerC** [comment]
I actually thought about this and this is what we did in FogROS1. If we use `~/.fogros2`, it might be possible in some scenarios that relative path ("~") does not work. We should at least leave a mark here, in case there will be any bugs of relative/absolute path in the future.  Another way of doing this is to use COLCON workspace's path.

**Comment by jeffi** [comment]
Under what scenarios would `~/.fogros2` not work?  We're using https://docs.python.org/3/library/os.path.html#os.path.expanduser for compatibility across OSes.

**Comment by KeplerC** [comment]
Oh this should work. I thought you were using "~" directly.
