### ISSUE TITLE
Add check that environment is properly set up for FogROS before launch

### ISSUE THREAD

**Issue by jeffi** [BerkeleyAutomation/FogROS2#40]
**Describe the bug**
When launching FogROS, it's possible to get far into the launch before observing an error that could have been caught early.  For example, setting `RMW_IMPLEMENTATION` incorrectly (not to the supported `rmw_cyclonedds_cpp`) or setting `CYCLONEDDS_URI` to point to an incompatible configuration file.

**To Reproduce**
1. Make sure `RMW_IMPLEMENTATION` and `CYCLONEDDS_URI` are both not set
2. Launch the talker example
3. Observe that the listener and talker either cannot communicate, or there may be an exception.

**Expected behavior**
At launch, before creating an instance, produce an error and fail if the environment variables are incorrectly set.

**Comment by KDharmarajanDev** [comment]
Resolved by #59
