### ISSUE TITLE
Investigate VPC usage in `aws.py`

### ISSUE THREAD

**Issue by jeffi** [BerkeleyAutomation/FogROS2#42]
Currently we assume that there is a VPC setup and present on the AWS account.  Do we need this?  If so, can we assume that the VPC that FogROS 2 finds is correctly set up? 

Without proper attention there seems to be 2 likely negative outcomes:
1. Accounts do not have VPCs setup, and launch process fails
2. Accounts have VPCs setup (perhaps multiple) that FogROS 2 will incorrectly select and either FogROS 2 won't work, or it will interfere with a separate VPC-based setup.

**Comment by KeplerC** [comment]
I believe the existing code comes from the [official tutorial](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/ec2-example-security-group.html#id5). It would be good if you can give a try, but I think it will work without any vpc

**Comment by jeffi** [comment]
It looks like the tutorial relies on having a VPC setup.  AWS does not guarantee that there will be a VPC.  The fix (3994b9ccc2be5a0aa37226f6c3f2f487f5da28dc) I put in is to find and use the default VPC if present, or create a default VPC and use it if not.
