### ISSUE TITLE
Avoid random name collisions

### ISSUE THREAD

**Issue by jeffi** [BerkeleyAutomation/FogROS2#49]
There is a small chance that random generation of instance names will result in a name collision.  Add some mechanism to check and avoid collisions (e.g., loop on name generation and check if such an instance already exists either locally or via the AWS api).

**Comment by SimeonOA** [comment]
@jeffi : Only happens now if a new instance has the same name with an active instance. The odds of this are currently low.

**Comment by SimeonOA** [comment]
Deal with Key-Pairs too!

**Comment by mjd3** [comment]
Closed by #68
