### ISSUE TITLE
ParamValidationError when `ros2 fog connect` is not given any arguments

### ISSUE THREAD

**Issue by mjd3** [BerkeleyAutomation/FogROS2#50]
**Describe the bug**
If a user mistakenly does not use the `-n` option for `ros2 fog connect`, they get a ParamValidationError.

**To Reproduce**
1. `docker run --rm -it --net=host --cap-add=NET_ADMIN fogros2`
2. `aws configure`
3. `ros2 launch fogros2_examples talker.aws.launch.py`
4. `ros2 fog connect`

**Expected behavior**
Should output an error message explaining usage of the `connect` cmd.

**Screenshots**
![image](https://user-images.githubusercontent.com/7028710/166805370-b7036832-5ac5-4472-9a7a-bb248185d898.png)

**Comment by mjd3** [comment]
Note that nearly the same behavior occurs when using `ros2 fog delete` with no arguments.
![image](https://user-images.githubusercontent.com/7028710/166806732-9eb82f48-e3e3-4083-96c9-1a253b49fad8.png)

**Comment by jeffi** [comment]
Probably best to make this bug apply to all CLI verbs--they likely have similar issues.
