### ISSUE TITLE
Docker talker/listener example results in rmw_cyclonedds_cpp error

### ISSUE THREAD

**Issue by mjd3** [BerkeleyAutomation/FogROS2#52]
**Describe the bug**
When running the talker/listener cloud example in a docker container, rmw_cyclonedds_cpp fails to create a domain because it is looking in the wrong place for the configuration file.

**To Reproduce**
1. `docker run -it --rm --net=host --cap-add=NET_ADMIN fogros2`
2. `aws configure`
3. `ros2 launch fogros2_examples talker.aws.launch.py`
4. See error below

**Expected behavior**
Listener should start on the remote machine and communicate with the talker.

**Screenshots**
![image](https://user-images.githubusercontent.com/7028710/166810708-1e73500e-b198-429d-8577-f3e5e720af0c.png)

**Comment by KeplerC** [comment]
This is because @jeffi updated install.md and not the main README.md. Should we keep two copies of the tutorial?

**Comment by mjd3** [comment]
Ah actually it is because the ros_entrypoint.sh script is not up to date for the current Dockerfile with jammy. I can fix it now.
