### ISSUE TITLE
`assert` only for logic errors, not configuration or user errors

### ISSUE THREAD

**Issue by jeffi** [BerkeleyAutomation/FogROS2#69]
**Describe the bug**
There appear to be a few cases where we use `assert` to test if a configuration is valid.  These should be changed to something that generates a message that indicates that it is user fixable.  `assert` implies that it there is a code logic error--something that should never happen, regardless of configuration.

**To Reproduce**
grep through code for `assert`  (there are a few in `aws.py`).  Assess if they're logic errors or user/configuration errors and update appropriately.

**Expected behavior**
Not possible for a user errors to generate an assert.

**Comment by mjd3** [comment]
Fixed by #75
