### ISSUE TITLE
Ubuntu 22.04 AMI contains both Humble and Rolling 

### ISSUE THREAD

**Issue by KDharmarajanDev** [BerkeleyAutomation/FogROS2#96]
**Describe the bug**
Current Ubuntu 22.04 AMI has both rolling and humble installed, leading to an issue where sourcing one of them doesn't actually allow the ros2 command to be found.

Specifically, the output error is `bash: line 1: ros2: command not found`.

**To Reproduce**
1. Run talker example with Ubuntu 22.04 and Humble (robot side)
2. Error occurs at command `source /opt/ros/humble/setup.bash && cd /home/ubuntu/fog_ws && colcon build --cmake-clean-cache && . /home/ubuntu/fog_ws/install/setup.bash && export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && export CYCLONEDDS_URI=file:///home/ubuntu/cyclonedds.xml && ROS_DOMAIN_ID=0 ros2 launch fogros2 cloud.launch.py`

**Expected behavior**
The ros2 command should be sourced properly, so that the talker example can be launched.

**Comment by jeffi** [comment]
Let's double check that the AMI is public.  This might be superseded by #101.
